# Generated by Django 4.1.3 on 2022-11-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("q01_products", models.CharField(max_length=256)),
                ("q02_project_name", models.CharField(max_length=256)),
                ("time_stamp", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
