# Generated by Django 4.1.3 on 2022-11-23 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matrix", "0002_survey_q07_license_survey_q08_license_other_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="survey",
            old_name="q08_license_other_Institutional",
            new_name="q08_license_other_institutional",
        ),
    ]
