# Generated by Django 4.1.3 on 2022-11-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matrix", "0005_survey_q10_indigenous_populations"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="q05_products_posted",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q05_products_posted_other",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q06_simulations",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
