# Generated by Django 4.1.3 on 2022-12-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matrix", "0007_survey_q64_email_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="random_id",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
