# Generated by Django 4.1.3 on 2023-02-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matrix", "0008_survey_random_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="q04_doi",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q04_doi_other",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q05_products_repo_other",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q14_nano_other",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q16_notebooks_other",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q16_notebooks_shared",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q17_notebooks_template",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q17_notebooks_template_other",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q18_software_license",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q18_software_license_other",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q19_api",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q20_api_versioned",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q22_ML_code",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q22_ML_code_other",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q25_ML_repro",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q25_ML_repro_consider_other",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q26_ML_models_other",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q26_ML_models_shared",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q27_domain_repo_other",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q28_dmp",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q28_yes_specify",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q29_register_repo",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q29_register_repo_other",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q30_schema_org",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q30_schema_yes_other",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="survey",
            name="q33_smart_api",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
